# Generated by Django 3.0.9 on 2020-08-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='token_manager.Pool'),
        ),
    ]
